# -*- coding: utf-8 -*-
"""ml1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qA4k7q0qMALJ2Zl2FqujVGJ8j4GVm1Dz
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sb

df = pd.read_csv('/content/sample_data/matches.csv')

df

maxsession = df['season'].value_counts().idxmax()
print(maxsession)

maxwin =  df['winner'].value_counts().idxmax()
print(maxwin)

df['venue'].value_counts()

sum = pd.concat([df['team1'], df['team2']])
print(sum)

wincsk = df['winner'].value_counts()
print(wincsk)

top = df['player_of_match'].value_counts()
print(top)



