# -*- coding: utf-8 -*-
"""ml2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dNhIpCij3-ShY0dTiN8KwsyydGp8Ja8e
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

df = pd.read_csv("/content/Movie-Dataset-Latest.csv")

df

mostpopuler =  df['popularity'].value_counts()
print(mostpopuler)

import matplotlib.pyplot as plt

most = df.loc[df['popularity'].idxmax()]
print(most)